name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-26.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Java Development Kit (JDK)
      uses: actions/setup-java@v5
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Cordova
      run: npm install -g cordova

    - name: Create Cordova Project
      run: |
        cordova create cordova_project com.deathwyler.portcode PORTCODE
        cd cordova_project
        rm -rf www/*
        cp -r ../index.html www/
        cordova platform add android@12.0.0
        cordova build android --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PORTCODE-APK
        path: cordova_project/platforms/android/app/build/outputs/apk/debug/app-debug.apk
